version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "32123:32123"  # Map container port 80 to host port 32123
    volumes:
      - ./code:/code
    environment:
      PYTHONPATH: /code/src

  db:
    image: "sqlite:latest"
    volumes:
      - ./code/src:/code/src
