services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map container port to host port
    volumes:
      - db-data:/code/data
      # how to set time to localtime instead of default UTC? I do NOT know! 
      #- /etc/localtime:/etc/localtime
      #- /etc/timezone:/etc/timezone
      
      - type: bind # use for dev container
        source: .
        target: /code

volumes:
  db-data: