services:
  app:
    container_name: nousa
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000" # host:container
    volumes:
      - db-data:/code/data

volumes:
  db-data: