services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #1 COMMENT = DEV CONTAINER!
    user: 3333:3333
    ports:
      - "5000:5000"  # host:container
    volumes:
      - db-data:/code/data
      #2 COMMENT = PRODUCTION CONTAINER!
      #- type: bind
      #  source: .
      #  target: /code

volumes:
  db-data: