version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map container port to host port
    volumes:
      - db-data:/code/data
      - type: bind #use for dev container
        source: .
        target: /code
    environment:
      - TZ=Europe/Amsterdam
    #  PYTHONPATH: /code/src

volumes:
  db-data: