version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map container port 32123 to host port 32123
    volumes:
      - db-data:/code/data
    #environment:
    #  PYTHONPATH: /code/src

volumes:
  db-data: