FROM python:3.12.4-slim
WORKDIR /code
RUN addgroup --gid 3333 nousa
RUN adduser --uid 3333 --gid 3333 --no-create-home --disabled-password --shell /usr/sbin/nologin nousa

# DEPENDENCIES
RUN apt-get update && apt-get install -y sqlite3

# PROGRAM FILES
COPY ./src ./src
COPY ./static ./static
COPY ./templates ./templates
COPY ./requirements.txt .
COPY ./alembic.ini .
RUN pip install -r requirements.txt --no-cache-dir
RUN chmod +x ./src/*.py
RUN chmod +x ./src/versions/*.py
EXPOSE 5000

# ENVIRONMENT VARIABLES
ENV PYTHONPATH="/code/src"

#
# ENV TZ="Europe/Berlin"
#
# ENV SENDER_EMAIL="send@example.com"
# ENV SENDER_PASSWORD="supersecretpassword"
#
# ENV RECEIVER_EMAIL="receive@example.com"
#
# ENV SMTP_SERVER="smtp.example.com"
# ENV SMTP_PORT=587
#

# USER
RUN mkdir -m 770 data
RUN chown -R 3333:3333 data

# LAUNCH!
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]