popular_tv_shows = (
    "The Rookie",
    "High Potential",
    "Doctor Odyssey",
    "Stranger Things",
    "Squid Game",
    "Wednesday",
    "Black Mirror",
    "Andor",
    "The Mandalorian",
    "The Witcher",
    "Bridgerton",
    "Yellowstone",
    "Euphoria",
    "Succession",
    "The Crown",
    "The Boys",
    "Ted Lasso",
    "The Morning Show",
    "Foundation",
    "Severance",
    "Only Murders in the Building",
    "The Handmaid's Tale",
    "Ozark",
    "Better Call Saul",
    "The Umbrella Academy",
    "Peaky Blinders",
    "The Marvelous Mrs. Maisel",
    "Lucifer",
    "The Sandman",
    "The Last of Us",
    "House of the Dragon",
    "The Lord of the Rings: The Rings of Power",
    "Arcane",
    "Invincible",
    "Fargo",
    "True Detective",
    "Westworld",
    "The White Lotus",
    "The Simpsons",
    "Family Guy",
    "Bob's Burgers",
    "South Park",
    "Rick and Morty",
    "American Horror Story",
    "Grey's Anatomy",
    "NCIS",
    "Law & Order: SVU",
    "Chicago Fire",
    "Chicago P.D.",
    "Chicago Med",
    "9-1-1",
    "Station 19",
    "Blue Bloods",
    "Magnum P.I.",
    "S.W.A.T.",
    "The Equalizer",
    "FBI",
    "FBI: Most Wanted",
    "FBI: International",
    "Young Sheldon",
    "Ghosts",
    "Abbott Elementary",
    "The Conners",
    "The Goldbergs",
    "Brooklyn Nine-Nine",
    "Superstore",
    "Parks and Recreation",
    "The Office",
    "Friends",
    "How I Met Your Mother",
    "Schitt's Creek",
    "Archer",
    "BoJack Horseman",
    "Big Mouth",
    "Solar Opposites",
    "Disenchantment",
    "The Dragon Prince",
    "Castlevania",
    "She-Ra and the Princesses of Power",
    "Cobra Kai",
    "The Karate Kid",
    "The Flash",
    "Supergirl",
    "Legends of Tomorrow",
    "Arrow",
    "Batwoman",
    "Stargirl",
    "Superman & Lois",
    "Titans",
    "Doom Patrol",
    "The Boys Presents: Diabolical",
    "What If...?",
    "Loki",
    "WandaVision",
    "The Falcon and the Winter Soldier",
    "Hawkeye",
    "Ms. Marvel",
    "Moon Knight",
    "She-Hulk",
    "Echo",
    "Ironheart",
    "Agatha: House of Harkness",
    "Secret Invasion",
    "Armor Wars",
    "I Am Groot"
)
